import fs from 'node:fs';
import os from 'node:os';
import { spawnSync } from 'node:child_process';

const evidenceDir = 'docs/evidence';
fs.mkdirSync(evidenceDir, { recursive: true });
const generatedAtUtc = new Date().toISOString();
const commitSha = spawnSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).stdout.trim();
const nodeVersion = process.version;
const npmVersion = spawnSync('npm', ['--version'], { encoding: 'utf8' }).stdout.trim();
const platform = `${os.type()} ${os.release()} ${os.arch()}`;
const commands = [
  ['npm', ['ci']],
  ['npm', ['run', 'verify:foundry']],
  ['npm', ['test']],
  ['npm', ['run', 'typecheck']],
  ['npm', ['run', 'lint']],
  ['npm', ['run', 'build']],
];
let text = '';
text += `UTC timestamp: ${generatedAtUtc}\n`;
text += `Commit SHA: ${commitSha}\n`;
text += `Node version: ${nodeVersion}\n`;
text += `npm version: ${npmVersion}\n`;
text += `OS: ${platform}\n\n`;
const results = [];
for (const [cmd, args] of commands) {
  const commandText = [cmd, ...args].join(' ');
  text += `===== COMMAND: ${commandText} =====\n`;
  const result = spawnSync(cmd, args, { encoding: 'utf8', shell: false });
  results.push({ command: commandText, exitCode: result.status ?? 1 });
  text += `Exit code: ${result.status ?? 1}\n`;
  text += `--- stdout ---\n${result.stdout ?? ''}\n`;
  text += `--- stderr ---\n${result.stderr ?? ''}\n\n`;
  if ((result.status ?? 1) !== 0) break;
}
fs.writeFileSync(`${evidenceDir}/m4.2-foundry-checks.txt`, text);
const failed = results.some((result) => result.exitCode !== 0);
const review = {
  schemaVersion: 1,
  stage: 'M4.2 Ember Foundry',
  commitSha,
  generatedAtUtc,
  overallAutomatedStatus: failed ? 'FAIL' : 'PASS',
  sourceMapPath: 'src/data/stages/foundry.json',
  checks: [
    {
      id: 'foundry-automated-review',
      requirement: 'GDD §2.6/§2.7 automated Foundry checks',
      status: failed ? 'FAIL' : 'PASS',
      measuredValue: results,
      expected: 'All commands exit 0',
      sourceFiles: ['scripts/review-m4.2.mjs', 'scripts/verify-foundry-stage.mjs'],
      sourceObjectIds: [],
      notes: 'Generated by npm run review:m4.2.',
    },
    {
      id: 'android-visible-landing',
      requirement: 'Manual Android validation: visible lava-fall landing before commitment',
      status: 'MANUAL_REQUIRED',
      measuredValue: null,
      expected: 'PO confirms on Android debug APK',
      sourceFiles: ['docs/evidence/m4.2-android-checklist.md'],
      sourceObjectIds: ['controlledDescent-lavafall'],
      notes: 'Camera/visual readability is not honestly proven by static geometry alone.',
    },
    {
      id: 'android-thumb-comfort',
      requirement: 'Manual Android validation: touch comfort and completion timing',
      status: 'MANUAL_REQUIRED',
      measuredValue: null,
      expected: 'PO records device, tester, blind/practiced times',
      sourceFiles: ['docs/evidence/m4.2-android-checklist.md'],
      sourceObjectIds: [],
      notes: 'Codex did not perform physical Android testing.',
    },
  ],
  manualChecksRemaining: ['android-visible-landing', 'android-thumb-comfort'],
};
fs.writeFileSync(`${evidenceDir}/m4.2-foundry-review.json`, `${JSON.stringify(review, null, 2)}\n`);
console.log(`Wrote ${evidenceDir}/m4.2-foundry-checks.txt`);
console.log(`Wrote ${evidenceDir}/m4.2-foundry-review.json`);
process.exit(failed ? 1 : 0);
